### ISSUE TITLE
ReadAndCollateSuiteResults does not use ConfigFile argument

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH#107]
When trying to use a different config to load scenarios for analysis, it is still using the existing GPE variables , this is not flexible

Repro scenario:
when GPE$globalConfigLoaded = TRUE (previously ran with some config)
switch to a set of results that is produced by a different config
Call something like 
` ReadAndCollateSuiteResults(dir="results", pattern="*_Ethiopia_AUG30_2022*", postProcFunc=simple_analysis, configFile = "config/MyDifferent_config.xlsx")`
the GPE is not refreshed with the config file passed in which may result in error if scenarios are different. 

I am not sure this is part of #69 discussion but I think analysis should be seperated to the simulation, We also need to document clear usage about the analysis pipeline

**Comment by rhanIDM** [comment]
The current solution is to post-process immediately after running simulations. This is the recommended practice for users.
