### ISSUE TITLE
ehep folder still exists post-release

### ISSUE THREAD

**Issue by BHagedorn-IDM** [InstituteforDiseaseModeling/PACE-HRH#187]
![image](https://user-images.githubusercontent.com/27299324/192632631-da2e399b-0e1d-4fc1-9e96-c5ef2f67433e.png)

Should this be removed? @celiot-IDM

**Comment by celiot-IDM** [comment]
@BHagedorn-IDM : Is it possible you either haven't synch'ed your repo in a while, or you're looking at an old branch?

This is what I see on my clone of the repo ...

![image](https://user-images.githubusercontent.com/53099836/192636697-005970a8-79df-49bb-a44f-1ff3420fa107.png)

... and this is what the GitHub site is showing ...

![image](https://user-images.githubusercontent.com/53099836/192636892-6c5cc3b5-8a11-4f43-b4eb-8f77ee0b2764.png)

**Comment by celiot-IDM** [comment]
https://github.com/InstituteforDiseaseModeling/PACE-HRH/pull/154 is the PR that removed the ehep directory from main.

**Comment by rhanIDM** [comment]
I also see ehep folder on main and after the most recent sync. It contains an empty folder inside.
![image](https://user-images.githubusercontent.com/108031190/192866281-1138fced-468c-46db-81e1-80b57a7b6700.png)
![image](https://user-images.githubusercontent.com/108031190/192866535-fd42541c-7754-484f-9664-9ca872ac7061.png)

**Comment by celiot-IDM** [comment]
Can we agree that if this doesn't repro with a fresh install, we can resolve this as "Won't Fix - No Repro"? (I'm happy to try to figure out what combination of previous installs and git's quirky handling of deletes got us here, but we might be the only people who will ever see this problem.)

**Comment by MeWu-IDM** [comment]
Yes , this folder is not tracked by Git anymore, one can remove it using this command https://git-scm.com/docs/git-clean (warning: use --dry-run first with caution or it will remove **everything** not tracked!)

**Comment by rhanIDM** [comment]
The issue can be closed by deleting the local ehep folder.
