### ISSUE TITLE
Stochasticity in mortality change rate may be too volatile

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH#190]
@rhanIDM found this when plotting Mortality (maleMortality$ratesMatrix)
![image](https://user-images.githubusercontent.com/108031190/192664301-bcf38f99-2578-4dfd-b9fc-f1f68e3ca8a4.png)
![image](https://user-images.githubusercontent.com/108031190/192664469-6ef55edb-219e-43fb-b46a-abeee6e80b39.png)

We can see that for 75+ the years after 2030 becomes very high, 
Examined  the code https://github.com/InstituteforDiseaseModeling/PACE-HRH/blob/main/pacehrh/R/pace_rates_matrix.R#L107-#L117
We found some issues:
 lims = p * q * c(-1, 1) is between(-0.35, 0.35)
(1) deltaRatios  is used twice in multiplication
(2) it is possible for  deltaRatios * (1 + e) to be a positive value even though deltaRatios < 1 (declining trend)

**Comment by MeWu-IDM** [comment]
This shows the probability of change for Annual delta mortality rates with p=0.22, q=1.6 the range seems too broad
![image](https://user-images.githubusercontent.com/40474438/192901671-4f890202-cbed-44c4-85d5-320ed7a2d6a0.png)

**Comment by rhanIDM** [comment]
Predictions of mortality rates after 50 trials, the range is particularly wide for age-band 75+:
![image](https://user-images.githubusercontent.com/108031190/192902931-e0cc1268-102b-4343-a026-b9a395158d25.png)
![image](https://user-images.githubusercontent.com/108031190/192903029-79837723-d327-4878-8c2d-41f07169ba62.png)

**Comment by celiot-IDM** [comment]
> (1) deltaRatios is used twice in multiplication
> (2) it is possible for deltaRatios * (1 + e) to be a positive value even though deltaRatios < 1 (declining trend)

Regarding (1): That definitely looks like a mistake. In the code snippet below, the first ref to deltaRatios should be removed.

`
     e <- deltaRatios * truncnorm::rtruncnorm(
        length(deltaRatios),
        mean = 0,
        sd = p,
        a = lims[1],
        b = lims[2]
      )
      deltas <- deltaRatios * (1 + e)
`

Regarding (2): @BHagedorn-IDM and I discussed this a while back. Yes, it can happen, but is that unrealistic behavior, especially in small populations? COVID, for example, is a contingency that drove death rates for over-65s up despite an underlying downward trend.

The histogram is what you expect to see for those input parameters. I agree that +/- 35% stochastic variation feels like a lot, but this part of the calculation (as opposed to the oops of multiplying by deltaRatios twice) is a GIGO effect.

**Comment by celiot-IDM** [comment]
BTW @rhanIDM and @MeWu-IDM : It's incredibly cool to see these plots being used for their intended purpose, ie spotting and fixing problems. Thank you!

**Comment by rhanIDM** [comment]
@celiot-IDM thank you for the clarification. Brittany also confirms that she picked the p & q to be in line with UN pop estimates, and she is comfortable with the behavior of the mean.

**Comment by celiot-IDM** [comment]
Thank you @rhanIDM for following up.

I'll make the computational correction and submit a PR for testing and evaluation.
