### ISSUE TITLE
some issues with pacehrh::SetRoundingLaw 

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH#195]
(1)
The function set GPE$roundingLaw but returns the previous state, this cause confusion as it prints out the previous state and confuses people https://github.com/InstituteforDiseaseModeling/PACE-HRH/blob/4ec5fd19e5e05c146964e2b46345e90bf90025a1/pacehrh/R/pace_config.R#L208

(2) When @rhanIDM tried with Bogus values it is not accepted but no warning message which can also cause confusion

**Comment by celiot-IDM** [comment]
Returning the previous value when setting a configuration option is a common pattern, and is used by R's option() command. From the documentation for option():
 
```
#set the editor, and save previous value
old.o <- options(editor = "nedit")
old.o
```
If you want to print the current state, SetRoundingState(NULL).

I'll add a trace message for bogus values.
