### ISSUE TITLE
Simplify analysis by using GetSuiteRates

### ISSUE THREAD

**Issue by MeWu-IDM** [InstituteforDiseaseModeling/PACE-HRH#212]
@rhanIDM Let's work on this task to simplify https://github.com/InstituteforDiseaseModeling/PACE-HRH/blob/rui/analysis_plots/analysis_scripts/Run_Sim_Plot_Population.R
and add documentation as necessary

**Comment by rhanIDM** [comment]
Achieved the goal to simplify demographics plotting by using pacehrh functions SaveSuiteDemographics() and GetSuiteRates().
