### ISSUE TITLE
misspelled function name

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH#218]
https://github.com/InstituteforDiseaseModeling/PACE-HRH/blob/66fbb93cde930b31abf4c7d42564dab3b280e76d/pacehrh/vignettes/technical-notes.Rmd#L72
Function 'setGlobalConfig()' does not exist. Should it have been 'loadGlobalConfig()'?

**Comment by celiot-IDM** [comment]
Actually, setGlobalConfig() *does* exist:

```
# Note: this function does not check that the file path is valid.
# This function is intended to support unit tests to force the system to
# initialize based on a different configuration than is in globalconfig.json.
setGlobalConfig <- function(inputExcelFilePath = "./config/model_inputs.xlsx"){
  if (!is.blank(inputExcelFilePath)){
    GPE$inputExcelFile <- inputExcelFilePath
    GPE$globalConfigLoaded <- TRUE
  }
}

```

It's defined in pace_config.R. It is not, however, an exported function, so it has to be access as `pacehrh:::setGlobalConfig()` (triple colon operator).

**Comment by rhanIDM** [comment]
Hi @celiot-IDM, thanks for the clarification. Should we update the technical notes to include this clarification as well? I suspect that future users are likely to name their input files differently from "model_inputs" especially if they have different versions of input files for different purposes. They may find this command particularly useful.

**Comment by celiot-IDM** [comment]
I'll have to think a bit about this, @rhanIDM. The implementation will cause strange side-effects outside the limited context of unit tests, so will need a bit of work to get right as a publicly available function.

**Comment by rhanIDM** [comment]
Both setGlobalConfig() and loadGlobalConfig() are private functions currently intended for supporting unit tests only. Will open a new issue exploring best practice for a user to load alternative input file to global environment.
