### ISSUE TITLE
Reference page in GetStarted should only contain public/exported functions

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH#222]
https://institutefordiseasemodeling.github.io/PACE-HRH/reference/index.html
Possibly caused by build_site command of pkgdown.

**Comment by MeWu-IDM** [comment]
build_site (build_reference) from pkgdown is building references from rd pages
after some research on https://roxygen2.r-lib.org/articles/rd.html#basics it says:
**_If you want to use roxygen2 documentation tags without generating an .Rd file, you can use @noRd to suppress file generation for a given topic. This is useful if you want to use roxygen2 conventions for documenting an internal function; only people reading the source doc will be able to read the docs._**
another way that also seems to work is to use `@keyword: internal`
as mentioned in https://community.rstudio.com/t/keywords-internal-vs-nord/35119
however I can't find the original reference from roxygen documentation about this feature (although I did try to run locally and it does remove the topic from index page)

@celiot-IDM we should only show the functions that users need to avoid confusions. Let's identify them and hide the internal ones

**Comment by celiot-IDM** [comment]
These functions were never intended to be public, so I'm going to start with them:

addRatesMatricesToPopulationChangeRates()
dispEnvs()
.computePopulationRangeMatrices()
gatherPopulation()
generatePrevalenceRatesMatrix()
generateRatesMatrix()
loadGlobalConfig()
loadInitialPopulation()
loadScenarios()
loadSeasonalityCurves()
loadSeasonalityOffsets()
loadStochasticParameters()
loadTaskParameters()
runSeasonalityExperiment()
traceMessage()
varyTaskValues()

**Comment by celiot-IDM** [comment]
Fixed by PR #281
