### ISSUE TITLE
Best way for a user to load alternative input file to global environment

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH#223]
Users are likely to name their input files differently from "model_inputs" and they may have different versions of input files for different purposes. We should update the user guide to include the process to load the intended input file to global configuration. We should also consider exporting loadGlobalConfig() to be a public function.

**Comment by celiot-IDM** [comment]
The "official" way to do this is to change the contents of globalconfig.json:

```
C:\Users\charlesel\Source\Ethiopia-HEP-Capacity-Analysis\pacehrh\tests>type globalconfig.json
{
  "configDirectoryLocation" : "./config",
  "inputExcelFile" : "model_inputs.xlsx",
  "suiteRngSeed" : 12345,
  "startYear" : 2020,
  "endYear" : 2040
}
```

A cheat (used a lot in the unit tests) to change just the input Excel file looks like this:

```
  gpe <- pacehrh:::GPE

  gpe$inputExcelFile <- "./simple_config/super_simple_inputs.xlsx"
  gpe$globalConfigLoaded <- TRUE

  pacehrh::InitializePopulation()
  # Etcetera
```

This cheat is implemented in the private function `setGlobalConfig()`. We could easily make `setGlobalConfig()` public, but might want to consider renaming it as it doesn't actually change all of the global configuration variables, just the Excel file name. I would also want to put some input validation into it if it's made public.

**Comment by rhanIDM** [comment]
Thank you for your explanation @celiot-IDM! The official way sounds good. I see that this is covered in the Technical notes. I will close this issue and point user to the Technical notes if this question ever comes up.
