### ISSUE TITLE
In Comprehensive Model, "Overhead_staff5" and "Overhead_staff6" should also be removed for Year<2030

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH#231]
https://github.com/InstituteforDiseaseModeling/PACE-HRH/blob/d81a61b461cf811534d6cbb514829304ea4126f0/pacehrh/R/pace_post_process.R#L37

<img width="259" alt="image" src="https://user-images.githubusercontent.com/108031190/215935049-0032cad2-c828-455b-a976-d64094edd062.png">

**Comment by celiot-IDM** [comment]
Addressed by #268
