### ISSUE TITLE
Change SetPerAgeStats() switch from "On/Off" to "Annual/Monthly/Off"

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH#235]
Can we possible change the "On/Off" to "Annual/Monthly/Off"? My impression is that when using .ComputePerAgeTaskTime, the .computeAnnualTaskTimes still can finish rather quickly, but .computeMonthlyTaskTimes takes significantly longer. The three options switch would allow the user to still have annual per age task times results for some basic analyses.

_Originally posted by @rhanIDM in https://github.com/InstituteforDiseaseModeling/PACE-HRH/pull/233#discussion_r1110470055_

**Comment by celiot-IDM** [comment]
Resolved as part of PR #233.

**Comment by rhanIDM** [comment]
Thank you so much @celiot-IDM!
