### ISSUE TITLE
Validation rules for reformatted cadres_ sheets

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH#254]
"StartYear" + cadre role + ScenarioID from "CadreRoles" sheet should uniquely identify a column of workload allocation on the "Cadres_Scenario" sheets.

**Comment by MeWu-IDM** [comment]
@rhanIDM let's calrify this
For example: if CadreRoles sheet define a startYear = 2020 endYear=2029 for RoleID=HEW1 for BasicModel (Cadres_Basic)
We should anticipate  these columns appear in Cadres_Basic to cover all years , correct?
startYear2020/HEW1
startYear2025/HEW1
startYear2030/HEW1

**Comment by rhanIDM** [comment]
The validations rules are:
1.) Sheet CadreRoles: columns StartYear and EndYear can not be outside of the model default range.
2.) Sheet CadreRoles: max(EndYear)+1 must appear in StartYear
3.) Sheet CadreRoles columns "ScenarioID" + "RoleID" + "StartYear" must appear in the corresponding cadre_ sheets' headers
4.) Sheet CadreRoles rows with no "EndYear" must appear in the max(StartYear) section in the corresponding cadre_ sheets'
5.) Check for continuity: each "RoleID" should appear in continuous sections on the cadre_ sheets' headers in between StartYear and EndYear.

**Comment by rhanIDM** [comment]
Revision for rule 5.) Also include CadreRoles rows with no "EndYear".
Add rule 6.) [the inverse of rule 3] on each scenario-specific cadre_sheet, the pair "StartYear" + "RoleID" must appear in CadreRoles for the corresponding ScenarioID (Error, print the StartYear and RoleID)

**Comment by rhanIDM** [comment]
Successfully implemented in v1.0.7.
