### ISSUE TITLE
Coverage rates feature test cases

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH#271]
1.) We will need to have a test in the 'possible errors' review section that checks to see if we parameterize the model to run for more years than is set up in the coverage tab. (e.g., run through 2050 but only provide 20 years of coverage rates). Expect to see error message.
2.) Empty coverage rates sheet with only header row should run and default all coverage rates to 1.
3.) Add scenario where coverage rate for a chosen task is set to be 25%, 50%, 75% and 100% for 5-year spans, and compare with the default scenario where coverage rate is always 100%.
4.) Test partially empty rows in coverage rates would still run, default empty cell value to 1.
5.) If the years are not consecutive, should get error message.
6.) If the task exists in coverage sheet, but not in taskvalues_ref sheet, ignore the task.
7) The code should check that the "sheet_Coverage" column in the "Scenario" tab is not empty and the sheet name specified must exist.

**Comment by MeWu-IDM** [comment]
Done: https://github.com/InstituteforDiseaseModeling/PACE-HRH/pull/279/commits/059551f29f0002659aebfea8cf4a5117acea9b07
