### ISSUE TITLE
Add a test to check that seasonality curves match up to task assignments

### ISSUE THREAD

**Issue by rhanIDM** [InstituteforDiseaseModeling/PACE-HRH#71]
The seasonality curves should applies to tasks listed on SeasonalityOffsets sheet. We could potentially test this by plotting the monthly estimated hours for these tasks (from results files) to confirm the seasonality curves are correctly applied.

**Comment by celiot-IDM** [comment]
Re-targeting for the V1.1 refresh (assuming still relevant).

**Comment by MeWu-IDM** [comment]
@rhanIDM we can close this if you are ok with the report from main branch

**Comment by celiot-IDM** [comment]
> @rhanIDM we can close this if you are ok with the report from main branch

I'm OK with closing if Rui is.

**Comment by rhanIDM** [comment]
Closing because the functionality is added to the model and the report produced during demo was satisfactory. Ran into a 'path' error while running on my machine but will discuss fix with @MeWu-IDM .
